# Generated by Django 4.0.4 on 2022-05-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EASS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='LevelNumber',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
