# Generated by Django 4.0.4 on 2022-05-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EASS', '0002_alter_level_levelnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(),
        ),
    ]
